--liquibase formatted sql


--changeset jackpot-service:0
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'jackpots'

-- =============================================================================
-- TABLE: jackpots
-- Description: Stores jackpot pools and strategy configurations (Fixed/Variable)
-- =============================================================================

CREATE TABLE jackpots (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    current_pool DECIMAL(19, 2) NOT NULL,
    initial_pool DECIMAL(19, 2) NOT NULL,
    contribution_type VARCHAR(16) NOT NULL,
    fixed_contribution_rate DECIMAL(19, 10),
    variable_initial_rate DECIMAL(19, 10),
    variable_min_rate DECIMAL(19, 10),
    variable_decrement_rate DECIMAL(19, 10),
    reward_type VARCHAR(16) NOT NULL,
    fixed_reward_chance DECIMAL(19, 10),
    variable_initial_chance DECIMAL(19, 10),
    variable_coefficient DECIMAL(19, 10),
    variable_limit_pool DECIMAL(19, 2),
    version BIGINT NOT NULL DEFAULT 0
);

COMMENT ON TABLE jackpots IS 'Stores jackpot pools and strategy configurations (Fixed/Variable)';

COMMENT ON COLUMN jackpots.id IS 'Unique identifier of the jackpot pool';
COMMENT ON COLUMN jackpots.name IS 'Human-readable name of the jackpot';
COMMENT ON COLUMN jackpots.current_pool IS 'Current balance of the jackpot pool';
COMMENT ON COLUMN jackpots.initial_pool IS 'Initial balance of the jackpot pool (reset value after a win)';
COMMENT ON COLUMN jackpots.contribution_type IS 'Type of contribution strategy (e.g., FIXED, VARIABLE)';
COMMENT ON COLUMN jackpots.fixed_contribution_rate IS 'Fixed contribution rate as a fraction of the bet stake';
COMMENT ON COLUMN jackpots.variable_initial_rate IS 'Initial contribution rate for variable strategy';
COMMENT ON COLUMN jackpots.variable_min_rate IS 'Minimum contribution rate for variable strategy';
COMMENT ON COLUMN jackpots.variable_decrement_rate IS 'Rate reduction per one monetary unit of pool growth';
COMMENT ON COLUMN jackpots.reward_type IS 'Type of reward strategy (e.g., FIXED, VARIABLE)';
COMMENT ON COLUMN jackpots.fixed_reward_chance IS 'Fixed winning probability as a fraction of 1.0';
COMMENT ON COLUMN jackpots.variable_initial_chance IS 'Initial winning probability for variable strategy';
COMMENT ON COLUMN jackpots.variable_coefficient IS 'Probability increase per one monetary unit of pool growth';
COMMENT ON COLUMN jackpots.variable_limit_pool IS 'Pool amount limit at which winning probability becomes 1.0';
COMMENT ON COLUMN jackpots.version IS 'Optimistic locking version for concurrent access control';

--rollback DROP TABLE jackpots;


--changeset jackpot-service:1
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'jackpot_contributions'

-- =============================================================================
-- TABLE: jackpot_contributions
-- Description: Tracks contributions to jackpots made by individual bets
-- =============================================================================

CREATE TABLE jackpot_contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64) NOT NULL,
    jackpot_id VARCHAR(64) NOT NULL,
    stake_amount DECIMAL(19, 2) NOT NULL,
    contribution_amount DECIMAL(19, 2) NOT NULL,
    current_jackpot_amount DECIMAL(19, 2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_contribution_jackpot FOREIGN KEY (jackpot_id) REFERENCES jackpots(id)
);

COMMENT ON TABLE jackpot_contributions IS 'Tracks historical bet contributions to jackpot pools';

COMMENT ON COLUMN jackpot_contributions.id IS 'Unique identifier of the contribution record';
COMMENT ON COLUMN jackpot_contributions.bet_id IS 'Unique identifier of the bet that triggered this contribution';
COMMENT ON COLUMN jackpot_contributions.user_id IS 'Unique identifier of the user who placed the bet';
COMMENT ON COLUMN jackpot_contributions.jackpot_id IS 'Identifier of the jackpot pool to which the contribution was made';
COMMENT ON COLUMN jackpot_contributions.stake_amount IS 'Stake amount of the bet';
COMMENT ON COLUMN jackpot_contributions.contribution_amount IS 'Amount contributed to the jackpot pool';
COMMENT ON COLUMN jackpot_contributions.current_jackpot_amount IS 'Jackpot pool amount immediately after this contribution';
COMMENT ON COLUMN jackpot_contributions.created_at IS 'Timestamp when the contribution was recorded';

CREATE INDEX idx_contributions_jackpot_id ON jackpot_contributions(jackpot_id);

--rollback DROP TABLE jackpot_contributions;


--changeset jackpot-service:2
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'jackpot_rewards'

-- =============================================================================
-- TABLE: jackpot_rewards
-- Description: Records winning reward payouts for jackpots
-- =============================================================================

CREATE TABLE jackpot_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64) NOT NULL,
    jackpot_id VARCHAR(64) NOT NULL,
    jackpot_reward_amount DECIMAL(19, 2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_reward_jackpot FOREIGN KEY (jackpot_id) REFERENCES jackpots(id)
);

COMMENT ON TABLE jackpot_rewards IS 'Records winning reward payouts for jackpots';

COMMENT ON COLUMN jackpot_rewards.id IS 'Unique identifier of the reward record';
COMMENT ON COLUMN jackpot_rewards.bet_id IS 'Unique identifier of the winning bet';
COMMENT ON COLUMN jackpot_rewards.user_id IS 'Unique identifier of the winning user';
COMMENT ON COLUMN jackpot_rewards.jackpot_id IS 'Identifier of the won jackpot pool';
COMMENT ON COLUMN jackpot_rewards.jackpot_reward_amount IS 'Paid out jackpot reward amount';
COMMENT ON COLUMN jackpot_rewards.created_at IS 'Timestamp when the reward was recorded';

CREATE INDEX idx_rewards_jackpot_id ON jackpot_rewards(jackpot_id);

--rollback DROP TABLE jackpot_rewards;


--changeset jackpot-service:3
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'jackpot_reward_evaluations'

-- =============================================================================
-- TABLE: jackpot_reward_evaluations
-- Description: Records the lottery evaluation results (won/lost) for each bet
-- =============================================================================

CREATE TABLE jackpot_reward_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64) NOT NULL,
    jackpot_id VARCHAR(64) NOT NULL,
    won BOOLEAN NOT NULL,
    evaluated_chance DECIMAL(19, 10) NOT NULL,
    random_value DECIMAL(19, 10) NOT NULL,
    reward_amount DECIMAL(19, 2),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_evaluation_jackpot FOREIGN KEY (jackpot_id) REFERENCES jackpots(id),
    CONSTRAINT fk_evaluation_contribution FOREIGN KEY (bet_id) REFERENCES jackpot_contributions(bet_id)
);

COMMENT ON TABLE jackpot_reward_evaluations IS 'Records lottery evaluation results (won/lost) for each bet';

COMMENT ON COLUMN jackpot_reward_evaluations.id IS 'Unique identifier of the evaluation record';
COMMENT ON COLUMN jackpot_reward_evaluations.bet_id IS 'Unique identifier of the evaluated bet';
COMMENT ON COLUMN jackpot_reward_evaluations.user_id IS 'Unique identifier of the user who placed the bet';
COMMENT ON COLUMN jackpot_reward_evaluations.jackpot_id IS 'Identifier of the evaluated jackpot pool';
COMMENT ON COLUMN jackpot_reward_evaluations.won IS 'Boolean flag indicating whether the bet won the jackpot';
COMMENT ON COLUMN jackpot_reward_evaluations.evaluated_chance IS 'Calculated probability of winning at the moment of evaluation';
COMMENT ON COLUMN jackpot_reward_evaluations.random_value IS 'Random value generated for evaluation (win if random_value < evaluated_chance)';
COMMENT ON COLUMN jackpot_reward_evaluations.reward_amount IS 'Reward amount paid out (if won)';
COMMENT ON COLUMN jackpot_reward_evaluations.created_at IS 'Timestamp when the evaluation was performed';

CREATE INDEX idx_evaluations_jackpot_id ON jackpot_reward_evaluations(jackpot_id);
CREATE INDEX idx_evaluations_bet_id ON jackpot_reward_evaluations(bet_id);

--rollback DROP TABLE jackpot_reward_evaluations;
